# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Install NVIDIA package pins
  become: yes
  ansible.builtin.copy:
    src: arvados-nvidia.pref
    dest: /etc/apt/preferences.d/arvados-nvidia.pref
    owner: root
    group: root
    mode: 0644
  when: "arvados_compute_pin_packages|bool"

- name: Install NVIDIA CUDA apt repository
  become: yes
  ansible.builtin.apt:
    deb: "https://developer.download.nvidia.com/compute/cuda/repos/{{ ansible_distribution|lower }}{{ ansible_distribution_version|replace('.', '') if ansible_distribution == 'Ubuntu' else ansible_distribution_major_version }}/{{ ansible_architecture }}/cuda-keyring_1.1-1_all.deb"
  notify:
    - apt update

- name: Install NVIDIA container toolkit apt repository
  become: yes
  ansible.builtin.deb822_repository:
    name: nvidia-container-toolkit
    types: deb
    uris: "{{ nvidia_container_apt_url }}/stable/deb/$(ARCH)"
    suites: "/"
    signed_by: "{{ nvidia_container_apt_url }}/gpgkey"
  notify:
    - apt update

- name: apt update if needed
  ansible.builtin.meta: flush_handlers

- name: Install NVIDIA CUDA build prerequisites
  become: yes
  ansible.builtin.apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"

- name: Install NVIDIA packages
  become: yes
  ansible.builtin.apt:
    name:
      - cuda
      - libnvidia-container1
      - libnvidia-container-tools
      - nvidia-container-toolkit

# NVIDIA packages include some services that are appropriate for desktops etc.
# but not compute nodes. Query which ones are installed and disable all found.
- name: Query NVIDIA services to disable
  become: yes
  ansible.builtin.systemd_service:
    name: "{{ item }}"
  loop:
    # This path triggers driver reloads when packages are upgraded.
    # That's not expected to happen on compute nodes.
    - nvidia-cdi-refresh.path
    # crunch-run has its own CUDA initialization code.
    # We prefer to use that over NVIDIA's.
    - nvidia-persistenced.service
  register: nvidia_services

- name: Disable unneeded NVIDIA services
  become: yes
  ansible.builtin.systemd_service:
    name: "{{ item.Id }}"
    enabled: false
  loop: "{{ nvidia_services.results|map(attribute='status')|selectattr('LoadState', '!=', 'not-found') }}"
