#!/bin/sh
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

# system one time tasks

PATH=/command:/sbin:/bin:/usr/sbin:/usr/bin

touch /run/runit.stopit
chmod 0 /run/runit.stopit
