#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh
. /usr/local/lib/arvbox/go-setup.sh

(cd /usr/local/bin && ln -sf arvados-server arvados-controller)

if test "$1" = "--only-deps" ; then
    exit
fi

flock /var/lib/arvados/cluster_config.yml.lock /usr/local/lib/arvbox/cluster-config.sh

exec /usr/local/lib/arvbox/runsu.sh /usr/local/bin/arvados-controller
