### Example inventory for install-arvados-cluster.yml ###
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# This file illustrates host groups you can deploy with
# install-arvados-cluster.yml and variables you can use to customize
# the deployment. Copy this file somewhere else, edit it following the
# comments, and run the installer like:
#   $ ansible-playbook -Ki YOUR-INVENTORY.yml install-arvados-cluster.yml

### Core cluster configuration settings ###
all:
  vars:
    # To deploy a cluster, you must write a cluster configuration file and have
    # a copy on the node where you run the Ansible installer. This file will be
    # deployed to cluster hosts as needed and read by the Ansible installer for
    # service configuration.
    # Refer to <https://doc.arvados.org/admin/config.html> for details.
    arvados_config_file: /PATH/TO/arvados/config.yml

    # This is the cluster identifier (five lowercase alphanumerics) for the
    # cluster configured in `arvados_config_file` that you want to deploy.
    arvados_cluster_id: xurid

    # If you are deploying a cluster to AWS, name the region you are deploying
    # to here. You can override this value per group or per host as needed.
    #aws_region: us-east-1

    # If specified, this file will be deployed to cluster hosts as
    # /etc/arvados/ca-certificates.crt. Arvados services use this file as a
    # source of trusted CA certificates.
    #arvados_certificates_file: /PATH/TO/ca-certificates.crt

    # `arvados_tls` defines the source of the TLS certificate for each Arvados
    # service. Each key corresponds to a key in the `Services` section of your
    # cluster configuration.
    arvados_tls:
      Controller:
        cert:
          # Path to the certificate on the managed node
          path: /PATH/TO/controller.pem
          # All of the following parameters are optional.
          # Set src for the `cert` and `key` files to deploy them from the
          # controller node to the hosts running this service. Otherwise, they
          # will be assumed to be at the specified paths.
          #src: /PATH/TO/controller.pem
          #owner: root
          #group: ssl-cert
          #mode: "0640" # mode must be quoted
        key:
          # path to the private key on the managed node
          path: /PATH/TO/controller.key
          # If the key file requires a passphrase stored in an AWS secret,
          # provide the name of that secret as `aws_secret`. This requires
          # you to set `aws_region` too.
          #aws_secret: ExampleSecretName
          # Also takes optional src, owner, group, and mode like cert
          #src: /PATH/TO/controller.key
          #owner: root
          #group: ssl-cert
          #mode: "0640" # mode must be quoted
      # Settings from this `Default` section will be used for any service that
      # does not have a specific configuration in `arvados_tls`. This is handy
      # to use if you have a wildcard certificate that can be used by most/all
      # of your cluster services.
      #Default:
      #  cert:
      #    path: /PATH/TO/arvados-cluster.pem
      #  key:
      #    path: /PATH/TO/arvados-cluster.key

    # `arvados_nginx_internal_networks` is a map of netmasks that should be
    # considered "internal" to the Arvados cluster. For each netmask key, if its
    # value is the literal `false`, it will be considered external. *Any* other
    # value will cause the netmask to be considered internal.
    #arvados_nginx_internal_networks:
    #  "10.0.0.0/8": true
    #  "172.16.0.0/12": true
    #  "192.168.0.0/16: true

    # By default, this playbook installs PostgreSQL packages from your
    # distribution. If you prefer to install a specific version from
    # postgresql.org (for example, to use the same version as a managed
    # database server), set `arvados_postgresql_version` to a major version
    # number like "18".
    #arvados_postgresql_version: "18"

### Host groups for core Arvados services ###
# Most Arvados clusters will have at least one host in each of these groups.
# It's normal to have the same host in multiple groups. For example, most
# clusters have the same host(s) in the `arvados_RailsAPI`,
# `arvados_Controller`, and `arvados_Websocket` groups.

# arvados_RailsAPI host(s) run the Arvados Rails API server.
arvados_RailsAPI:
  hosts:
    api.arvados.example:
  vars:
    # If your cluster will use an external database, specify the database
    # superuser credentials here. These will be used to set up a dedicated
    # Arvados role and database.
    #arvados_database_login_user: ""
    #arvados_database_login_password: ""

# arvados_Controller host(s) run the Arvados API controller.
arvados_Controller:
  hosts:
    api.arvados.example:
  vars:
    # `arvados_nginx_server_config` is a block of nginx configuration
    # directives that will be included in the server block for this
    # service. You can use this to answer to additional names or ports,
    # or do whatever other customization you need.
    #arvados_nginx_server_config: |
    #  server_name  arvados.example;

# arvados_Websocket host(s) run the Arvados websockets server.
arvados_Websocket:
  hosts:
    api.arvados.example:

# arvados_Keepstore host(s) run the Arvados keepstore services.
arvados_Keepstore:
  hosts:
    keep0.arvados.example:
    keep1.arvados.example:

# arvados_Keepbalance host(s) run the Arvados keep-balance service.
arvados_Keepbalance:
  hosts:
    keep0.arvados.example:
    keep1.arvados.example:

# arvados_Keepproxy host(s) run the Arvados keepproxy service.
arvados_Keepproxy:
  hosts:
    keep.arvados.example:

# arvados_WebDAV host(s) run the Arvados keep-web/WebDAV service.
arvados_WebDAV:
  hosts:
    webdav.arvados.example:

# arvados_Workbench2 host(s) serve the Arvados Workbench front-end.
arvados_Workbench2:
  hosts:
    workbench.arvados.example:


### Host groups for Arvados dispatchers ###
# A complete Arvados cluster must deploy at least one dispatcher, but
# different clusters run different dispatchers. Uncomment and define the
# group(s) for the dispatcher(s) your cluster will run.

# arvados_DispatchCloud host(s) run the arvados-dispatch-cloud service
# to create dedicated cloud nodes to configure containers. You must have
# `Containers.CloudVMs` configured in your cluster configuration for this
# to work.
#arvados_DispatchCloud:
#  hosts:
#    api.arvados.example:

# arvados_DispatchLocal host(s) run the crunch-dispatch-local service
# to run containers on the local host. This is only intended for small
# development clusters, not production use. These hosts will automatically
# have compute requirements like Docker and arv-mount installed.
#arvados_DispatchLocal:
#  hosts:
#    compute0.arvados.example:
#    compute1.arvados.example:


### Host groups for Arvados supporting services ###
# These groups deploy services that can make an Arvados cluster easier to
# deploy or use, but they are not required for all clusters. Uncomment and
# define the group(s) for the services you want to run.

# arvados_PostgreSQL host(s) will have the PostgreSQL server installed to host
# the cluster database. The Ansible installer currently does minimal server
# configuration and does not set up replication or other high-level features.
# You do not need this group if your cluster uses an externally managed database
# (e.g., Amazon RDS).
#arvados_PostgreSQL:
#  hosts:
#    api.arvados.example:
#  vars:
#    # `arvados_postgresql_hba_sources` is an array of IPv4 or v6 netmasks,
#    # or special values recognized in `pg_hba.conf`. The Arvados database user
#    # will be allowed to connect from these sources. This must be configured
#    # so that all cluster services are allowed to connect to the database.
#    arvados_postgresql_hba_sources:
#      - samenet
#    # `arvados_postgresql_hba_method` defines the PostgreSQL authentication
#    # method that will be accepted for the Arvados database user. Set this
#    # to `md5` if your distribution includes a version of PostgreSQL too old
#    # to support `scram-sha-256`.
#    arvados_postgresql_hba_method: scram-sha-256
#    # If you need to do advanced database setup, refer to other settings in
#    # `roles/arvados_postgresql/defaults/main.yml`.

# arvados_Shell host(s) have all client tools installed so cluster users can
# access a complete client environment via SSH or similar.
#arvados_Shell:
#  hosts:
#    shell.arvados.example:
#      # The installer will automatically create an Arvados virtual machine
#      # record for each shell node. The `hostname` attribute in that record
#      # will come from the inventory hostname by default. If you need to use
#      # a different hostname externally, set `arvados_shell_hostname` like this:
#      #arvados_shell_hostname: shellhost.arvados.example


### Centralized logging ###
# The installer can set up Prometheus to collect logs from all Arvados services
# and report metrics.
# This is especially helpful to collate logs on multi-node installs.
# The Arvados cluster activity report can use these metrics to report additional
# information about cluster health.

# arvados_Loki host(s) will have Loki installed from the Grafana APT repository.
# The required Loki configuration file is defined by `arvados_loki_config_file`.
# Typically this should be installed on all nodes running Arvados services as
# illustrated in the example below.
#arvados_Loki:
#  children:
#    arvados_RailsAPI:
#    arvados_Controller:
#    arvados_Websocket:
#    arvados_Keepstore:
#    arvados_Keepbalance:
#    arvados_Keepproxy:
#    arvados_WebDAV:
#    arvados_Workbench2:
#    arvados_DispatchCloud:
#    arvados_DispatchLocal:
#  vars:
#    arvados_loki_config_file: /PATH/TO/config.yml

# arvados_Alloy host(s) will have Alloy installed from the Grafana APT repository.
# The required Alloy configuration file is defined by `arvados_alloy_config_file`.
#arvados_Alloy:
#  hosts:
#    prometheus.arvados.example:
#  vars:
#    arvados_alloy_config_file: /PATH/TO/config.alloy

# arvados_Grafana host(s) will have Grafana installed from the Grafana APT repository.
# The required Grafana configuration file is defined by `arvados_grafana_config_file`.
#arvados_Grafana:
#  hosts:
#    prometheus.arvados.example:
#  vars:
#    arvados_grafana_config_file: /PATH/TO/grafana.ini

# arvados_Prometheus host(s) will have Prometheus installed from the Prometheus APT repository.
# The required Prometheus configuration file is defined by `arvados_prometheus_config_file`.
#arvados_Prometheus:
#  hosts:
#    prometheus.arvados.example:
#  vars:
#    arvados_prometheus_config_file: /PATH/TO/prometheus.yml
