#!/bin/sh

set -e

INSTALL_PATH=/var/www/arvados-sso
RELEASE_PATH=$INSTALL_PATH/current
SHARED_PATH=$INSTALL_PATH/shared
CONFIG_PATH=/etc/arvados/sso

remove () {
  rm -f $RELEASE_PATH/config/database.yml
  rm -f $RELEASE_PATH/config/environments/production.rb
  rm -f $RELEASE_PATH/config/application.yml
  rm -rf $RELEASE_PATH/public/assets/
  rm -rf $RELEASE_PATH/tmp
  rm -rf $RELEASE_PATH/.bundle
  rm $RELEASE_PATH/log
}

if [ "$1" = 'remove' ]; then
  remove
fi
