#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

. /usr/local/lib/arvbox/common.sh
exec /usr/local/lib/arvbox/keep-setup.sh keep1 ${services[keepstore1]}
