#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh

cd /usr/src/sso
if test -s /var/lib/arvados/sso_rails_env ; then
  export RAILS_ENV=$(cat /var/lib/arvados/sso_rails_env)
else
  export RAILS_ENV=development
fi

run_bundler --without=development
bundle exec passenger-config build-native-support
bundle exec passenger-config install-standalone-runtime

if test "$1" = "--only-deps" ; then
    exit
fi

set -u

if ! test -s /var/lib/arvados/sso_uuid_prefix ; then
  ruby -e 'puts "#{rand(2**64).to_s(36)[0,5]}"' > /var/lib/arvados/sso_uuid_prefix
fi
uuid_prefix=$(cat /var/lib/arvados/sso_uuid_prefix)

if ! test -s /var/lib/arvados/sso_secret_token ; then
  ruby -e 'puts rand(2**400).to_s(36)' > /var/lib/arvados/sso_secret_token
fi
secret_token=$(cat /var/lib/arvados/sso_secret_token)

if ! test -s /var/lib/arvados/self-signed.key ; then
  openssl req -new -x509 -nodes -out /var/lib/arvados/self-signed.pem -keyout /var/lib/arvados/self-signed.key -days 365 -subj '/CN=localhost'
fi

cat >config/application.yml <<EOF
$RAILS_ENV:
  uuid_prefix: $uuid_prefix
  secret_token: $secret_token
  default_link_url: "http://$localip"
  allow_account_registration: true
EOF

(cd config && /usr/local/lib/arvbox/application_yml_override.py)

if ! test -f /var/lib/arvados/sso_database_pw ; then
    ruby -e 'puts rand(2**128).to_s(36)' > /var/lib/arvados/sso_database_pw
fi
database_pw=$(cat /var/lib/arvados/sso_database_pw)

if ! (psql postgres -c "\du" | grep "^ arvados_sso ") >/dev/null ; then
    psql postgres -c "create user arvados_sso with password '$database_pw'"
    psql postgres -c "ALTER USER arvados_sso CREATEDB;"
fi

sed "s/password:.*/password: $database_pw/" <config/database.yml.example >config/database.yml

if ! test -f /var/lib/arvados/sso_database_setup ; then
   bundle exec rake db:setup

   if ! test -s /var/lib/arvados/sso_app_secret ; then
       ruby -e 'puts rand(2**400).to_s(36)' > /var/lib/arvados/sso_app_secret
   fi
   app_secret=$(cat /var/lib/arvados/sso_app_secret)

   bundle exec rails console <<EOF
c = Client.new
c.name = "joshid"
c.app_id = "arvados-server"
c.app_secret = "$app_secret"
c.save!
EOF

   touch /var/lib/arvados/sso_database_setup
fi

rm -rf tmp
mkdir -p tmp/cache

bundle exec rake assets:precompile
bundle exec rake db:migrate

set +u
if test "$1" = "--only-setup" ; then
    exit
fi

exec bundle exec passenger start --port=${services[sso]} \
     --ssl --ssl-certificate=/var/lib/arvados/self-signed.pem \
     --ssl-certificate-key=/var/lib/arvados/self-signed.key
