# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Install PostgreSQL server package
  become: yes
  ansible.builtin.apt:
    name:
      - "postgresql{{ arvados_postgresql_suffix }}"

- name: Setup PostgreSQL service
  when: "ansible_virtualization_type != 'docker'"
  ansible.builtin.include_tasks: setup_service.yml
