#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh
. /usr/local/lib/arvbox/go-setup.sh

(cd /usr/local/bin && ln -sf arvados-server arvados-git-httpd)

if test "$1" = "--only-deps" ; then
    exit
fi

/usr/local/lib/arvbox/runsu.sh flock $ARVADOS_CONTAINER_PATH/cluster_config.yml.lock /usr/local/lib/arvbox/cluster-config.sh

export PATH="$PATH:$ARVADOS_CONTAINER_PATH/git/bin"
cd ~git
exec /usr/local/bin/arvados-git-httpd
