#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh
. /usr/local/lib/arvbox/go-setup.sh

flock /var/lib/gopath/gopath.lock go get -t "git.curoverse.com/arvados.git/services/arv-git-httpd"
install $GOPATH/bin/arv-git-httpd /usr/local/bin

if test "$1" = "--only-deps" ; then
    exit
fi

export ARVADOS_API_HOST=$localip:${services[api]}
export ARVADOS_API_HOST_INSECURE=1
export PATH="$PATH:/var/lib/arvados/git/bin"
cd ~git

exec /usr/local/bin/arv-git-httpd \
    -address=:${services[arv-git-httpd]} \
    -git-command=/usr/share/gitolite3/gitolite-shell \
    -gitolite-home=/var/lib/arvados/git \
    -repo-root=/var/lib/arvados/git/repositories
