#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

.  /usr/local/lib/arvbox/common.sh

if test "$1" != "--only-deps" ; then
  while [ ! -f $ARVADOS_CONTAINER_PATH/api.ready ]; do
    sleep 1
  done
fi

cd /usr/src/workbench2

yarn install

if test "$1" = "--only-deps" ; then
    exit
fi

API_HOST=${localip}:${services[controller-ssl]}

if test -f /usr/src/workbench2/public/API_HOST ; then
    API_HOST=$(cat /usr/src/workbench2/public/API_HOST)
fi

cat <<EOF > /usr/src/workbench2/public/config.json
{
  "API_HOST": "$API_HOST"
}
EOF

export ARVADOS_API_HOST=$localip:${services[controller-ssl]}
export ARVADOS_API_TOKEN=$(cat $ARVADOS_CONTAINER_PATH/superuser_token)

url_prefix="https://$localip:${services[workbench2-ssl]}/"

set +e
read -rd $'\000' apiclient <<EOF
{
   "url_prefix": "$url_prefix",
   "is_trusted": true
}
EOF
set -e

clientuuid=$(arv --format=uuid api_client list --filters '[["url_prefix", "=", "'$url_prefix'"]]')
if [[ -n "$clientuuid" ]] ; then
    arv api_client update --uuid $clientuuid --api-client "$apiclient"
else
    arv api_client create --api-client "$apiclient"
fi

# Can't use "yarn start", need to run the dev server script
# directly so that the TERM signal from "sv restart" gets to the
# right process.
export VERSION=$(./version-at-commit.sh)
export BROWSER=none
export CI=true
export HTTPS=false
node --version
exec node node_modules/react-scripts/scripts/start.js
