# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

FROM arvados/arvbox-base
ARG arvados_version

RUN ln -sf /usr/src/arvados/tools/arvbox/lib/arvbox/docker/service /etc
RUN mkdir -p /var/lib/arvbox
RUN echo "development" > /var/lib/arvbox/api_rails_env
RUN echo "development" > /var/lib/arvbox/sso_rails_env
RUN echo "development" > /var/lib/arvbox/workbench_rails_env

RUN mkdir /etc/test-service && \
    ln -sf /var/lib/arvbox/service/postgres /etc/test-service && \
    ln -sf /var/lib/arvbox/service/certificate /etc/test-service
RUN mkdir /etc/devenv-service