FROM arvados/arvbox-base
ARG arvados_version

ADD service/ /var/lib/arvbox/service
RUN rmdir /etc/service && ln -sf /var/lib/arvbox/service /etc

RUN mkdir /etc/test-service && ln -sf /var/lib/arvbox/service/postgres /etc/test-service
