# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Include role only on Debian-based distros
  ansible.builtin.include_role:
    name: distro_apt
  when: "ansible_pkg_mgr == 'apt'"

- name: Install Docker apt package pins
  become: yes
  ansible.builtin.copy:
    src: arvados-docker.pref
    dest: /etc/apt/preferences.d/arvados-docker.pref
    owner: root
    group: root
    mode: 0644
  when: "ansible_pkg_mgr == 'apt' and arvados_compute_pin_packages|bool"

- name: Clean-up Docker dnf package pins
  become: yes
  community.general.dnf_versionlock:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-ce-rootless-extras
    state: absent
  when: "ansible_pkg_mgr == 'dnf' and arvados_compute_pin_packages|bool"

- name: Install current Docker dnf package pins
  become: yes
  community.general.dnf_versionlock:
    name:
      - containerd.io-{{ docker_dnf_pin_version['containerd.io'] }}
      - docker-ce-{{ docker_dnf_pin_version['docker-ce'] }}
      - docker-ce-cli-{{ docker_dnf_pin_version['docker-ce-cli'] }}
      - docker-ce-rootless-extras-{{ docker_dnf_pin_version['docker-ce-rootless-extras'] }}
    state: present
  when: "ansible_pkg_mgr == 'dnf' and arvados_compute_pin_packages|bool"

- name: Install Docker apt repository
  become: yes
  when: "ansible_pkg_mgr == 'apt'"
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "{{ docker_apt_url }}"
    suites: "{{ ansible_distribution_release }}"
    components: stable
    signed_by: "{{ docker_apt_url }}/gpg"
  notify:
    - apt update

- name: Install Docker dnf repository
  become: yes
  when: "ansible_pkg_mgr == 'dnf'"
  ansible.builtin.yum_repository:
    name: docker
    description: Docker-CE repository
    baseurl: "{{ docker_dnf_url }}/$releasever/$basearch/stable"
    gpgcheck: true
    gpgkey:  "{{ docker_dnf_url }}/gpg"

- name: apt update if needed
  when: "ansible_pkg_mgr == 'apt'"
  ansible.builtin.meta: flush_handlers

- name: Install Docker apt package
  become: yes
  when: "ansible_pkg_mgr == 'apt'"
  ansible.builtin.apt:
    name: docker-ce
    install_recommends: false

- name: Install Docker dnf packages
  become: yes
  when: "ansible_pkg_mgr == 'dnf'"
  ansible.builtin.dnf:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-ce-rootless-extras
    state: latest
