// Copyright (C) The Arvados Authors. All rights reserved.
//
// SPDX-License-Identifier: AGPL-3.0

export const tooltips = {
    multiProject: [
        'Move to',
        'Move to trash',
    ],
    adminProject: [
        'View details',
        'Open in new tab',
        'Copy UUID',
        'Share',
        'Edit project',
        'Move to trash',
        'New project',
        'Move to',
        'Freeze project',
        'Add to favorites',
        'Add to public favorites',
        'Copy link to clipboard',
        'Open with 3rd party client',
        'API Details',
    ],
    adminFrozenProject: [
        'View details',
        'Open in new tab',
        'Copy UUID',
        'Share',
        'Unfreeze project',
        'Add to favorites',
        'Add to public favorites',
        'Copy link to clipboard',
        'Open with 3rd party client',
        'API Details',
    ],
    nonAdminProject: [
        'View details',
        'Open in new tab',
        'Copy UUID',
        'Share',
        'Edit project',
        'Move to trash',
        'New project',
        'Move to',
        'Freeze project',
        'Add to favorites',
        'Copy link to clipboard',
        'Open with 3rd party client',
        'API Details',
    ],
    readOnlyProject: [
        'View details',
        'Open in new tab',
        'Copy UUID',
        'Add to favorites',
        'Copy link to clipboard',
        'Open with 3rd party client',
        'API Details',
    ],
    multiCollection: [
        'Move to',
        'Make a copy',
        'Move to trash',
    ],
    adminCollection: [
        'View details',
        'Open in new tab',
        'Copy UUID',
        'Share',
        'Edit collection',
        'Move to trash',
        'Make a copy',
        'Move to',
        'Add to favorites',
        'Add to public favorites',
        'Copy link to clipboard',
        'Open with 3rd party client',
        'API Details',
    ],
    readonlyCollection: [
        'View details',
        'Open in new tab',
        'Copy UUID',
        'Make a copy',
        'Add to favorites',
        'Copy link to clipboard',
        'Open with 3rd party client',
        'API Details',
    ],
    readonlyMultiCollection: [
        'Make a copy',
    ],
    multiProcess: [
        'Remove',
    ],
    adminRunningProcess: [
        'View details',
        'Open in new tab',
        'Copy UUID',
        'Copy and re-run process',
        'Cancel',
        'Edit process',
        'Remove',
        'Outputs',
        'Add to favorites',
        'Add to public favorites',
        'Copy link to clipboard',
        'API Details',
    ],
    adminOnHoldProcess: [
        'View details',
        'Open in new tab',
        'Copy UUID',
        'Copy and re-run process',
        'Edit process',
        'Remove',
        'Outputs',
        'Add to favorites',
        'Add to public favorites',
        'Copy link to clipboard',
        'API Details',
    ],
};