#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh
. /usr/local/lib/arvbox/go-setup.sh

flock /var/lib/gopath/gopath.lock go get -t "git.curoverse.com/arvados.git/services/crunch-run"
flock /var/lib/gopath/gopath.lock go get -t "git.curoverse.com/arvados.git/services/crunch-dispatch-local"
install $GOPATH/bin/crunch-run $GOPATH/bin/crunch-dispatch-local /usr/local/bin

if test "$1" = "--only-deps" ; then
    exit
fi

cat > /usr/local/bin/crunch-run.sh <<EOF
#!/bin/sh
exec /usr/local/bin/crunch-run -container-enable-networking=always -container-network-mode=host \$@
EOF
chmod +x /usr/local/bin/crunch-run.sh

export ARVADOS_API_HOST=$localip:${services[api]}
export ARVADOS_API_HOST_INSECURE=1
export ARVADOS_API_TOKEN=$(cat /var/lib/arvados/superuser_token)

exec /usr/local/bin/crunch-dispatch-local -crunch-run-command=/usr/local/bin/crunch-run.sh -poll-interval=1
