// Copyright (C) The Arvados Authors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

package service

import (
	"context"
)

type contextKey string

var contextKeyServiceToken contextKey = "serviceToken"

// Token returns the privileged system token suitable for the given
// service context.
//
// It only works on contexts that were generated by Command() and
// passed to a Handler. For other contexts it returns the empty
// string.
func Token(ctx context.Context) string {
	t, _ := ctx.Value(contextKeyServiceToken).(string)
	return t
}

// tokenContext returns a child context with the given token attached
// so it can be retrieved by Token().
func tokenContext(ctx context.Context, t string) context.Context {
	return context.WithValue(ctx, contextKeyServiceToken, t)
}
