#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -eux -o pipefail

. /usr/local/lib/arvbox/common.sh

cat > /etc/slurm-llnl/slurm.conf  <<EOF
ControlMachine=$HOSTNAME
ControlAddr=$HOSTNAME
AuthType=auth/munge
DefaultStorageLoc=/var/log/slurm-llnl
SelectType=select/cons_res
SelectTypeParameters=CR_CPU_Memory
SlurmUser=arvbox
SlurmdUser=arvbox
SlurmctldPort=7002
SlurmctldTimeout=300
SlurmdPort=7003
SlurmdSpoolDir=/var/tmp/slurmd.spool
SlurmdTimeout=300
StateSaveLocation=/var/tmp/slurm.state
NodeName=$HOSTNAME
PartitionName=compute State=UP Default=YES Nodes=$HOSTNAME
EOF

mkdir -p /var/run/munge

/usr/sbin/munged -f

exec /usr/sbin/slurmctld -v -D
