#!/usr/bin/env rake

require "rubygems"
require "colorize"

require "zenweb/tasks"
load "zenweb-textile.rb"
load "zenweb-liquid.rb"

file "sdk/python/arvados/index.html" do |t|
  `which epydoc`
  if $? == 0
    `epydoc --html -o sdk/python/arvados arvados`
    Dir["sdk/python/arvados/*"].each do |f|
      puts f
      $website.pages[f] = Zenweb::Page.new($website, f)
    end
  else
    puts "Warning: epydoc not found, Python documentation will not be generated".colorize(:light_red)
  end
end

task :extra_wirings do
  $website.pages["sdk/python/python.html.textile.liquid"].depends_on("sdk/python/arvados/index.html")
end
