#!/usr/bin/env bash

# usage:
# "restart-dns-server <path-to-restart.txt>" (restart now if needed)
# or
# "restart-dns-server <path-to-restart.txt> -d" (wait for restart to be needed, restart, repeat)

RESTART_TXT_PATH=$1

if [[ "$RESTART_TXT_PATH" == "" ]]; then
  echo
  echo "Usage: "
  echo "   $0 <path-to-restart.txt>      # restart now if needed"
  echo "   $0 <path-to-restart.txt> -d   # wait for restart to be needed, restart, repeat"
  echo
  exit 1
fi

while :
do
  if [ -e $RESTART_TXT_PATH ]; then
    RESTART_COMMAND=`cat $RESTART_TXT_PATH`
    echo "restart command: $RESTART_COMMAND"
    rm -f "$RESTART_TXT_PATH"
    echo restarting
    $RESTART_COMMAND
  fi
  if [ "-d" = "$2" ]
  then
    sleep 2
  else
    exit 0
  fi
done
