// Copyright (C) The Arvados Authors. All rights reserved.
//
// SPDX-License-Identifier: AGPL-3.0

import * as React from 'react';
import AccessTime from '@material-ui/icons/AccessTime';
import ArrowDropDown from '@material-ui/icons/ArrowDropDown';
import BubbleChart from '@material-ui/icons/BubbleChart';
import Cached from '@material-ui/icons/Cached';
import Code from '@material-ui/icons/Code';
import ChevronLeft from '@material-ui/icons/ChevronLeft';
import ChevronRight from '@material-ui/icons/ChevronRight';
import Close from '@material-ui/icons/Close';
import ContentCopy from '@material-ui/icons/ContentCopy';
import CreateNewFolder from '@material-ui/icons/CreateNewFolder';
import Delete from '@material-ui/icons/Delete';
import Edit from '@material-ui/icons/Edit';
import Folder from '@material-ui/icons/Folder';
import GetApp from '@material-ui/icons/GetApp';
import Help from '@material-ui/icons/Help';
import Inbox from '@material-ui/icons/Inbox';
import Info from '@material-ui/icons/Info';
import Input from '@material-ui/icons/Input';
import Menu from '@material-ui/icons/Menu';
import MoreVert from '@material-ui/icons/MoreVert';
import Notifications from '@material-ui/icons/Notifications';
import People from '@material-ui/icons/People';
import Person from '@material-ui/icons/Person';
import PersonAdd from '@material-ui/icons/PersonAdd';
import PlayArrow from '@material-ui/icons/PlayArrow';
import RateReview from '@material-ui/icons/RateReview';
import Search from '@material-ui/icons/Search';
import Star from '@material-ui/icons/Star';
import StarBorder from '@material-ui/icons/StarBorder';

export const AddFavoriteIcon = (className?: string) => <StarBorder className={className} />;
export const AdvancedIcon = (className?: string) => <Folder className={className} />;
export const CustomizeTableIcon = (className?: string) => <Menu className={className} />;
export const CopyIcon = (className?: string) => <ContentCopy className={className} />;
export const CollectionIcon = (className?: string) => <Folder className={className} />;
export const CloseIcon = (className?: string) => <Close className={className} />;
export const DefaultIcon = (className?: string) => <RateReview className={className} />;
export const DetailsIcon = (className?: string) => <Info className={className} />;
export const DownloadIcon = (className?: string) => <GetApp className={className} />;
export const FavoriteIcon = (className?: string) => <Star className={className} />;
export const HelpIcon = (className?: string) => <Help className={className} />;
export const LogIcon = (className?: string) => <Folder className={className} />;
export const MoreOptionsIcon = (className?: string) => <MoreVert className={className} />;
export const MoveToIcon = (className?: string) => <Input className={className} />;
export const NewProjectIcon = (className?: string) => <CreateNewFolder className={className} />;
export const NotificationIcon = (className?: string) => <Notifications className={className} />;
export const PaginationDownIcon = (className?: string) => <ArrowDropDown className={className} />;
export const PaginationLeftArrowIcon = (className?: string) => <ChevronLeft className={className} />;
export const PaginationRightArrowIcon = (className?: string) => <ChevronRight className={className} />;
export const ProcessIcon = (className?: string) => <BubbleChart className={className} />;
export const ProjectIcon = (className?: string) => <Folder className={className} />;
export const ProjectsIcon = (className?: string) => <Inbox className={className} />;
export const ProvenanceGraphIcon = (className?: string) => <Folder className={className} />;
export const RecentIcon = (className?: string) => <AccessTime className={className} />;
export const RemoveIcon = (className?: string) => <Delete className={className} />;
export const RemoveFavoriteIcon = (className?: string) => <Star className={className} />;
export const RenameIcon = (className?: string) => <Edit className={className} />;
export const ReRunProcessIcon = (className?: string) => <Cached className={className} />;
export const SearchIcon = (className?: string) => <Search className={className} />;
export const ShareIcon = (className?: string) => <PersonAdd className={className} />;
export const ShareMeIcon = (className?: string) => <People className={className} />;
export const SidePanelRightArrowIcon = (className?: string) => <PlayArrow className={className} />;
export const TrashIcon = (className?: string) => <Delete className={className} />;
export const UserPanelIcon = (className?: string) => <Person className={className} />;
export const UsedByIcon = (className?: string) => <Folder className={className} />;
export const WorkflowIcon = (className?: string) => <Code className={className} />;