# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Set up /etc/arvados
  become: yes
  ansible.builtin.file:
    state: directory
    path: /etc/arvados
    owner: root
    group: root
    mode: 0755

- name: Write Arvados config.yml
  no_log: yes
  when: arvados_config_file is truthy
  become: yes
  ansible.builtin.copy:
    src: "{{ arvados_config_file }}"
    dest: /etc/arvados/config.yml
    owner: root
    group: "{{ arvados_config_group }}"
    mode: 0640
  register: arvados_config_copy

# The `arvados_config_changed` fact is permanently set true
# if `/etc/arvados/config.yml` is ever changed.
- name: Record if config.yml changed
  no_log: yes # Not sure if there's a risk of leaking a secret in a diff output here
  ansible.builtin.set_fact:
    arvados_config_changed: "{{ arvados_config_changed|default(false) or arvados_config_copy.changed }}"

- name: Write Arvados certificates
  when: arvados_certificates_file is truthy
  become: yes
  ansible.builtin.copy:
    src: "{{ arvados_certificates_file }}"
    dest: /etc/arvados/ca-certificates.crt
    owner: root
    group: root
    mode: 0644
