#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -eux -o pipefail

. /usr/local/lib/arvbox/common.sh

mkdir -p ~/.pip /var/lib/pip
cat > ~/.pip/pip.conf <<EOF
[global]
download_cache = /var/lib/pip
EOF

cd /usr/src/arvados/sdk/cli
run_bundler --binstubs=$PWD/binstubs
ln -sf /usr/src/arvados/sdk/cli/binstubs/arv /usr/local/bin/arv

# Need to install the upstream version of pip because the python-pip package
# shipped with Debian 9 is patched to change behavior in a way that breaks our
# use case.
# See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876145
# When a non-root user attempts to install system packages, it makes the
# --ignore-installed flag the default (and there is no way to turn it off),
# this has the effect of making it very hard to share dependencies shared among
# multiple packages, because it will blindly install the latest version of each
# dependency requested by each package, even if a compatible package version is
# already installed.
pip_install pip

pip_install wheel

cd /usr/src/arvados/sdk/python
python setup.py sdist
pip_install $(ls dist/arvados-python-client-*.tar.gz | tail -n1)

cd /usr/src/arvados/services/fuse
python setup.py sdist
pip_install $(ls dist/arvados_fuse-*.tar.gz | tail -n1)

cd /usr/src/arvados/sdk/cwl
python setup.py sdist
pip_install $(ls dist/arvados-cwl-runner-*.tar.gz | tail -n1)
