#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -eux -o pipefail

. /usr/local/lib/arvbox/common.sh

cd /usr/src/arvados/sdk/ruby
run_bundler
bundler_binstubs

cd /usr/src/arvados/sdk/cli
run_bundler
bundler_binstubs

python_srcdir="$(mktemp --directory --tmpdir pysrc.XXXXXXXX)"
trap 'rm -rf "$python_srcdir"' EXIT INT TERM QUIT
for subdir in sdk/python services/fuse sdk/cwl; do
    env -C "/usr/src/arvados/$subdir" \
        /opt/arvados-py/bin/python3 setup.py sdist --dist-dir="$python_srcdir"
done
/opt/arvados-py/bin/pip install "$python_srcdir"/*
