#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -eux -o pipefail

exec /usr/local/lib/arvbox/runsu.sh /usr/sbin/slurmd -v -D
