#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

.  /usr/local/lib/arvbox/common.sh

cd /usr/src/composer

npm -d install --prefix /usr/local --global yarn

yarn install

if test "$1" = "--only-deps" ; then
    exit
fi

cat >/usr/src/composer/src/composer.yml <<EOF
API_HOST: ${localip}:${services[controller-ssl]}
EOF
exec node_modules/.bin/ng serve --host 0.0.0.0 --port 4200 --env=webdev --ssl=true --sslCert="${server_cert}" --sslKey="${server_cert_key}"
