# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Configure Docker daemon
  become: yes
  ansible.builtin.copy:
    content: "{{ docker_daemon|dict2items|selectattr('value', '!=', '_OMIT_')|items2dict|to_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: docker
    mode: 0640
  notify:
    - stop docker

- name: Install Docker cleaner
  become: yes
  ansible.builtin.apt:
    name: arvados-docker-cleaner

- name: Create Docker cleaner configuration directories
  become: yes
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
  loop:
    - /etc/arvados
    - /etc/arvados/docker-cleaner

- name: Configure Docker cleaner
  become: yes
  ansible.builtin.copy:
    content: "{{ docker_cleaner|to_json }}"
    dest: /etc/arvados/docker-cleaner/docker-cleaner.json
    owner: root
    group: root
    mode: 0644
