# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

# Vagrantfile API/syntax version. Don"t touch unless you know what you"re doing!
VAGRANTFILE_API_VERSION = "2".freeze

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.ssh.forward_x11 = true

  config.vm.define "arvados" do |arv|
    arv.vm.box = "bento/debian-10"
    arv.vm.hostname = "arva2.arv.local"
    # Networking
    arv.vm.network "forwarded_port", guest: 8443, host: 8443
    arv.vm.network "forwarded_port", guest: 25100, host: 25100
    arv.vm.network "forwarded_port", guest: 9002, host: 9002
    arv.vm.network "forwarded_port", guest: 9000, host: 9000
    arv.vm.network "forwarded_port", guest: 8900, host: 8900
    arv.vm.network "forwarded_port", guest: 8002, host: 8002
    arv.vm.network "forwarded_port", guest: 8001, host: 8001
    arv.vm.network "forwarded_port", guest: 8000, host: 8000
    arv.vm.network "forwarded_port", guest: 3001, host: 3001
    # config.vm.network "private_network", ip: "192.168.33.10"
    # arv.vm.synced_folder "salt_pillars", "/srv/pillars",
    #                      create: true
    arv.vm.provision "shell",
                     path: "provision.sh",
                     args: [
                       "--vagrant",
                       "--ssl-port=8443"
                     ].join(" ")
  end
end
