# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

arvados_postgresql_version: ""
arvados_postgresql_repository: "{{ 'postgresql' if arvados_postgresql_version is truthy else 'distro' }}"
arvados_postgresql_suffix: "{{ ('-' ~ arvados_postgresql_version) if arvados_postgresql_version is truthy else '' }}"
