#!/bin/bash

exec 2>&1
set -eux -o pipefail

. /usr/local/lib/arvbox/common.sh

mkdir -p ~/.pip /var/lib/arvados/pip
cat > ~/.pip/pip.conf <<EOF
[global]
download_cache = /var/lib/arvados/pip
EOF

cd /usr/src/arvados/sdk/cli
run_bundler --binstubs=$PWD/binstubs
ln -sf /usr/src/arvados/sdk/cli/binstubs/arv /usr/local/bin/arv

cd /usr/src/arvados/sdk/python
python setup.py sdist
pip_install $(ls dist/arvados-python-client-*.tar.gz | tail -n1)

cd /usr/src/arvados/services/fuse
python setup.py sdist
pip_install $(ls dist/arvados_fuse-*.tar.gz | tail -n1)
