# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'
gemspec
gem 'rake'
gem 'minitest', '>= 5.0.0'
gem 'mocha', require: false
gem 'signet', '<= 0.11'
