# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Install Prometheus
  become: yes
  ansible.builtin.apt:
    name: prometheus

- name: Write Prometheus config
  when: arvados_ansible_services.Prometheus.ConfigFile is defined
  become: yes
  no_log: yes
  ansible.builtin.copy:
    src: "{{ arvados_ansible_services.Prometheus.ConfigFile }}"
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: prometheus
    mode: 0640
  register: arvados_prometheus_config_copy

- name: Start and enable prometheus
  become: yes
  ansible.builtin.systemd_service:
    name: prometheus.service
    state: "{{ 'restarted' if arvados_prometheus_config_copy.changed else 'started' }}"
    enabled: true
