# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'
gem 'responders', '~> 2.0'

group :test, :development do
  gem 'factory_bot_rails'
  gem 'database_cleaner'

  # As of now (2019-03-27) There's an open issue about incompatibilities with
  # newer versions of this gem: https://github.com/rails/rails-perftest/issues/38
  gem 'ruby-prof', '~> 0.15.0'

  # Note: "require: false" here tells bunder not to automatically
  # 'require' the packages during application startup. Installation is
  # still mandatory.
  gem 'test-unit', '~> 3.0', require: false
  gem 'simplecov', '~> 0.7.1', require: false
  gem 'simplecov-rcov', require: false
  gem 'mocha', require: false
  gem 'byebug'
end

gem 'pg', '~> 1.0'

gem 'multi_json'
gem 'oj'

gem 'therubyracer'
gem 'uglifier', '~> 2.0'

gem 'jquery-rails'

gem 'rvm-capistrano', :group => :test

gem 'acts_as_api'

gem 'passenger'

# Locking to 5.10.3 to workaround issue in 5.11.1 (https://github.com/seattlerb/minitest/issues/730)
gem 'minitest', '5.10.3'

# Restricted because omniauth >= 1.5.0 requires Ruby >= 2.1.9:
gem 'omniauth', '~> 1.4.0'
gem 'omniauth-oauth2', '~> 1.1'

gem 'andand'

gem 'optimist'
gem 'faye-websocket'

gem 'themes_for_rails', git: 'https://github.com/curoverse/themes_for_rails'

# We need arvados-cli because of crunchv1. Note: bundler can't handle
# two gems with the same "git" url but different "glob" values, hence
# the use of a wildcard here instead of literal paths
# (sdk/cli/arvados-cli.gem and sdk/ruby/arvados.gem).
gem 'arvados-cli', git: 'https://github.com/curoverse/arvados.git', glob: 'sdk/*/*.gemspec', branch: '15900-gem-version-142'
gem 'arvados', git: 'https://github.com/curoverse/arvados.git', glob: 'sdk/*/*.gemspec', branch: '15900-gem-version-142'
gem 'httpclient'

gem 'sshkey'
gem 'safe_yaml'
gem 'lograge'
gem 'logstash-event'

gem 'rails-observers'

gem 'rails-perftest'
gem 'rails-controller-testing'

gem 'sass-rails'

# arvados-google-api-client and googleauth depend on signet, but
# signet 0.12 is incompatible with ruby 2.3.
gem 'signet', '< 0.12'

# Install any plugin gems
Dir.glob(File.join(File.dirname(__FILE__), 'lib', '**', "Gemfile")) do |f|
    eval(IO.read(f), binding)
end
