# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

source 'https://rubygems.org'

gem 'rails', '~> 4.2'
gem 'responders', '~> 2.0'
gem 'protected_attributes'

group :test, :development do
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'ruby-prof'
  # Note: "require: false" here tells bunder not to automatically
  # 'require' the packages during application startup. Installation is
  # still mandatory.
  gem 'test-unit', '~> 3.0', require: false
  gem 'simplecov', '~> 0.7.1', require: false
  gem 'simplecov-rcov', require: false
  gem 'mocha', require: false
end

# We'll need to update related code prior to Rails 5.
# See: https://github.com/rails/activerecord-deprecated_finders
gem 'activerecord-deprecated_finders', require: 'active_record/deprecated_finders'

# pg is the only supported database driver.
# Note: Rails 4.2 is not compatible with pg 1.0
#       (See: https://github.com/rails/rails/pull/31671)
gem 'pg', '~> 0.18'

gem 'multi_json'
gem 'oj'
gem 'oj_mimic_json'

# for building assets
gem 'sass-rails',   '~> 4.0'
gem 'coffee-rails', '~> 4.0'
gem 'therubyracer'
gem 'uglifier', '~> 2.0'

gem 'jquery-rails'

gem 'rvm-capistrano', :group => :test

gem 'acts_as_api'

gem 'passenger'

# Restricted because omniauth >= 1.5.0 requires Ruby >= 2.1.9:
gem 'omniauth', '~> 1.4.0'
gem 'omniauth-oauth2', '~> 1.1'

gem 'andand'

gem 'test_after_commit', :group => :test

gem 'trollop'
gem 'faye-websocket'

gem 'themes_for_rails', git: 'https://github.com/curoverse/themes_for_rails'

gem 'arvados', '>= 0.1.20150615153458'
gem 'arvados-cli', '>= 0.1.20161017193526'
gem 'httpclient'

gem 'sshkey'
gem 'safe_yaml'
gem 'lograge'
gem 'logstash-event'

gem 'rails-observers'

# Install any plugin gems
Dir.glob(File.join(File.dirname(__FILE__), 'lib', '**', "Gemfile")) do |f|
    eval(IO.read(f), binding)
end
