#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

begin
  ok = PgPower
rescue
  abort "Hm, pg_power is missing. Make sure you use 'bundle exec rake ...'"
end

Server::Application.load_tasks
