#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

begin
  ok = PgPower
rescue
  abort "Hm, pg_power is missing. Make sure you use 'bundle exec rake ...'"
end

Server::Application.load_tasks

namespace :test do
  task(:run).clear
  # Copied from the definition in Rails 3.2.
  # This may need to be updated if we upgrade Rails.
  task :run do
    errors = %w(test:units test:functionals test:integration test:tasks).collect do |task|
      begin
        Rake::Task[task].invoke
        nil
      rescue => e
        { :task => task, :exception => e }
      end
    end.compact

    if errors.any?
      puts errors.map { |e| "Errors running #{e[:task]}! #{e[:exception].inspect}" }.join("\n")
      abort
    end
  end
end

namespace :db do
  namespace :structure do
    task :dump do
      require 'tempfile'
      origfnm = File.expand_path('../db/structure.sql', __FILE__)
      tmpfnm = Tempfile.new 'structure.sql', File.expand_path('..', origfnm)
      begin
        tmpfile = File.new tmpfnm, 'w'
        origfile = File.new origfnm
        origfile.each_line do |line|
          if /^SET lock_timeout = 0;/ =~ line
            # Avoid edit wars between versions that do/don't write this line.
            next
          elsif /^COMMENT ON EXTENSION/ =~ line
            # Avoid warning message when loading:
            # "structure.sql:22: ERROR:  must be owner of extension plpgsql"
            tmpfile.write "-- "
          end
          tmpfile.write line
        end
        origfile.close
        tmpfile.close
        File.rename tmpfnm, origfnm
        tmpfnm = false
      ensure
        File.unlink tmpfnm if tmpfnm
      end
    end
  end
end
