# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: restart grafana
  become: yes
  ansible.builtin.systemd_service:
    name: grafana-server.service
    state: restarted
