### This file is managed by Ansible ###
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

[Unit]
Wants=arvados_aws_secret.service
After=arvados_aws_secret.service
