#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

set -e

. /usr/local/lib/arvbox/common.sh

git config --system "credential.http://$localip:${services[arv-git-httpd]}/.username" none
git config --system "credential.http://$localip:${services[arv-git-httpd]}/.helper" '!cred(){ cat >/dev/null; if [ "$1" = get ]; then echo password=$ARVADOS_API_TOKEN; fi; };cred'

/usr/local/lib/arvbox/runsu.sh $0-service

cd /usr/src/arvados/services/login-sync

export ARVADOS_API_HOST=$localip:${services[api]}
export ARVADOS_API_HOST_INSECURE=1
export ARVADOS_API_TOKEN=$(cat /var/lib/arvados/superuser_token)
export ARVADOS_VIRTUAL_MACHINE_UUID=$(cat /var/lib/arvados/vm-uuid)

while true ; do
      bundle exec arvados-login-sync
      sleep 120
done
