#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

set -e

. /usr/local/lib/arvbox/common.sh

git config --system "credential.http://$localip:${services[arv-git-httpd]}/.username" none
git config --system "credential.http://$localip:${services[arv-git-httpd]}/.helper" '!cred(){ cat >/dev/null; if [ "$1" = get ]; then echo password=$ARVADOS_API_TOKEN; fi; };cred'

/usr/local/lib/arvbox/runsu.sh $0-service

cd /usr/src/arvados/services/login-sync

export ARVADOS_API_HOST=$localip:${services[controller-ssl]}
export ARVADOS_API_HOST_INSECURE=1
export ARVADOS_API_TOKEN=$(cat $ARVADOS_CONTAINER_PATH/superuser_token)
export ARVADOS_VIRTUAL_MACHINE_UUID=$(cat $ARVADOS_CONTAINER_PATH/vm-uuid)

while true ; do
      /usr/src/arvados/services/login-sync/binstubs/arvados-login-sync
      sleep 120
done
