#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
sleep 2
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh

cd /usr/src/arvados/services/login-sync
run_bundler --binstubs=$PWD/binstubs
ln -sf /usr/src/arvados/services/login-sync/binstubs/arvados-login-sync /usr/local/bin/arvados-login-sync

if test "$1" = "--only-deps" ; then
    exit
fi

set -u

export ARVADOS_API_HOST=$localip:${services[controller-ssl]}
export ARVADOS_API_HOST_INSECURE=1
export ARVADOS_API_TOKEN=$(cat $ARVADOS_CONTAINER_PATH/superuser_token)
export ARVADOS_VIRTUAL_MACHINE_UUID=$(cat $ARVADOS_CONTAINER_PATH/vm-uuid)

set +e
read -rd $'\000' vm <<EOF
{
 "uuid": "$ARVADOS_VIRTUAL_MACHINE_UUID",
 "hostname":"$localip"
}
EOF
set -e

if arv virtual_machine get --uuid $ARVADOS_VIRTUAL_MACHINE_UUID ; then
    arv virtual_machine update --uuid $ARVADOS_VIRTUAL_MACHINE_UUID --virtual-machine "$vm"
else
    arv virtual_machine create --virtual-machine "$vm"
fi
