#!/bin/sh
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

if test -n "$JOB_PARAMETER_CRUNCHRUNNER" ; then
    exec $TASK_KEEPMOUNT/$JOB_PARAMETER_CRUNCHRUNNER
else
    exec /usr/local/bin/crunchrunner
fi
