#!/usr/bin/env python

import arvados
import arvados_cwl
import arvados.collection
import arvados.util
from cwltool.process import shortname
import cwltool.main
import logging
import os
import json
import argparse
from arvados.api import OrderedJsonModel
from cwltool.process import adjustFiles

api = arvados.api("v1")

try:
    job_order_object = arvados.current_job()['script_parameters']

    print job_order_object

    def keeppath(v):
        if arvados.util.keep_locator_pattern.match(v):
            return "file://%s/%s" % (os.environ['TASK_KEEPMOUNT'], v)

    job_order_object["cwl:tool"] = keeppath(job_order_object["cwl:tool"])

    adjustFiles(job_order_object, keeppath)

    runner = arvados_cwl.ArvCwlRunner(api_client=arvados.api('v1', model=OrderedJsonModel()))

    t = cwltool.main.load_tool(job_order_object, False, True, runner.arvMakeTool, True)

    np = argparse.Namespace()
    np.project_uuid = arvados.current_job()["owner_uuid"]
    np.enable_reuse = True
    np.submit = False
    outputObj = runner.arvExecutor(t, job_order_object, "", np, cwl_runner_job=arvados.current_job())

    files = {}
    def capture(path):
        sp = path.split("/")
        col = sp[0][5:]
        if col not in files:
            files[col] = set()
        files[col].add("/".join(sp[1:]))
        return path

    adjustFiles(outputObj, capture)

    final = arvados.collection.Collection()

    for k,v in files.iteritems():
        with arvados.collection.Collection(k) as c:
            for f in c:
                final.copy(f, f, c, True)

    def makeRelative(path):
        return "/".join(path.split("/")[1:])

    adjustFiles(outputObj, makeRelative)

    with final.open("cwl.output.json", "w") as f:
        json.dump(outputObj, f, indent=4)

    api.job_tasks().update(uuid=arvados.current_task()['uuid'],
                                         body={
                                             'output': final.save_new(create_collection_record=False),
                                             'success': True,
                                             'progress':1.0
                                         }).execute()
except Exception as e:
    logging.exception("Unhandled exception")
    api.job_tasks().update(uuid=arvados.current_task()['uuid'],
                                         body={
                                             'output': None,
                                             'success': False,
                                             'progress':1.0
                                         }).execute()
