#! /usr/bin/env ruby

# list_generated_files file1 file2...
#
# Prints a list of the "generated" files that correspond to the files
# listed on the command line.
#
# e.g.:
# list_generated_files keep/config.rb.in api/application.yml.in
# -> keep/generated/config.rb api/generated/application.yml

print ARGV.collect { |f|
  File.join(File.dirname(f), "generated", File.basename(f, ".in"))
}.join(" "), "\n"
