// Copyright (C) The Arvados Authors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

package arvados

import "github.com/prometheus/client_golang/prometheus"

type KeepClientMetrics struct {
	BackendBytes    *prometheus.CounterVec
	BackendBytesIn  prometheus.Counter
	BackendBytesOut prometheus.Counter
	ClientOps       *prometheus.CounterVec
	ClientOpsGet    prometheus.Counter
	ClientOpsPut    prometheus.Counter
	Cache           *prometheus.CounterVec
	CacheMisses     prometheus.Counter
	CacheHits       prometheus.Counter
}

func NewKeepClientMetrics() KeepClientMetrics {
	var m KeepClientMetrics
	m.BackendBytes = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: "arvados",
		Subsystem: "keepclient",
		Name:      "backend_bytes",
		Help:      "network traffic generated by keepclient",
	}, []string{"direction"})
	m.BackendBytesIn = m.BackendBytes.WithLabelValues("in")
	m.BackendBytesOut = m.BackendBytes.WithLabelValues("out")
	m.ClientOps = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: "arvados",
		Subsystem: "keepclient",
		Name:      "ops",
		Help:      "keepclient operations requested by application",
	}, []string{"op"})
	m.ClientOpsGet = m.ClientOps.WithLabelValues("get")
	m.ClientOpsPut = m.ClientOps.WithLabelValues("put")
	m.Cache = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: "arvados",
		Subsystem: "keepclient",
		Name:      "cache",
		Help:      "keepclient disk cache events",
	}, []string{"event"})
	m.CacheMisses = m.Cache.WithLabelValues("miss")
	m.CacheHits = m.Cache.WithLabelValues("hit")
	return m
}

func (m *KeepClientMetrics) Register(reg *prometheus.Registry) error {
	for _, c := range []prometheus.Collector{m.BackendBytes, m.ClientOps, m.Cache} {
		err := reg.Register(c)
		if err != nil {
			return err
		}
	}
	return nil
}
