version: '2'
services:
  sys0:
    build: ../test-debian8
    cap_add:
      - IPC_LOCK
      - SYS_ADMIN
    volumes:
      - ../arvados-admin:/usr/bin/arvados-admin:ro
      - ./agent.yml:/etc/arvados/agent/agent.yml:ro
      - ./encrypt-key.txt:/var/lib/arvados/encrypt-key.txt:ro
      - ./master-token.txt:/var/lib/arvados/master-token.txt:ro
      - vault:/var/lib/arvados/vault
    command: ["bash", "-c", "runsvdir /etc/sv & arvados-admin setup -unseal=true -init-vault=true && wait"]
  sys1:
    build: ../test-debian8
    cap_add:
      - IPC_LOCK
      - SYS_ADMIN
    volumes:
      - ../arvados-admin:/usr/bin/arvados-admin:ro
      - ./agent.yml:/etc/arvados/agent/agent.yml:ro
      - ./encrypt-key.txt:/var/lib/arvados/encrypt-key.txt:ro
      - ./master-token.txt:/var/lib/arvados/master-token.txt:ro
      - vault:/var/lib/arvados/vault
    command: ["bash", "-c", "runsvdir /etc/sv & arvados-admin setup -unseal=true && wait"]
  sys2:
    build: ../test-debian8
    cap_add:
      - IPC_LOCK
      - SYS_ADMIN
    volumes:
      - ../arvados-admin:/usr/bin/arvados-admin:ro
      - ./agent.yml:/etc/arvados/agent/agent.yml:ro
      - ./encrypt-key.txt:/var/lib/arvados/encrypt-key.txt:ro
      - ./master-token.txt:/var/lib/arvados/master-token.txt:ro
      - vault:/var/lib/arvados/vault
    command: ["bash", "-c", "runsvdir /etc/sv & arvados-admin setup -unseal=true && wait"]
volumes:
  vault:
