# Suggested Git configuration for Arvados
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# Arvados standards forbid trailing whitespace.
# Configure Git to highlight it.
[color "diff"]
whitespace = red reverse

[core]
whitespace = trailing-space

[merge]
# Merges to main should never be fast-forward.
# Easiest to turn it off by default:
ff = false

[user]
# The Arvados DCO sign-off requires your real name and email.
# Refer to CONTRIBUTING.md for full details.
#name = Your Name
#email = yourmail@example.local

[trailer.arvados]
key = Arvados-DCO-1.1-Signed-off-by
ifexists = doNothing
# If you uncomment cmd, the prepare-commit-msg hook will prepare commit
# messages with your DCO sign-off, which attests you have permission to
# contribute the code. Refer to CONTRIBUTING.md for full terms.
#cmd = echo \"$(git config user.name) <$(git config user.email)>\"
