#!/bin/bash

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh

cd /usr/src/arvados/services/api
export RAILS_ENV=development

run_bundler --without=development
bundle exec passenger start --runtime-check-only --runtime-dir=/var/lib/passenger

if test "$1" = "--only-deps" ; then
    exit
fi

flock /var/lib/arvados/api.lock /usr/local/lib/arvbox/api-setup.sh

set +u
if test "$1" = "--only-setup" ; then
    exit
fi

exec bundle exec passenger start --port=${services[api]} \
                  --runtime-dir=/var/lib/passenger \
                  --ssl --ssl-certificate=/var/lib/arvados/self-signed.pem \
                  --ssl-certificate-key=/var/lib/arvados/self-signed.key
