#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh

cd /usr/src/arvados/services/api
export RAILS_ENV=development

run_bundler --without=development
bundle exec passenger-config build-native-support
bundle exec passenger-config install-standalone-runtime

if test "$1" = "--only-deps" ; then
    exit
fi

flock /var/lib/arvados/api.lock /usr/local/lib/arvbox/api-setup.sh

set +u
if test "$1" = "--only-setup" ; then
    exit
fi

exec bundle exec passenger start --port=${services[api]} \
                  --ssl --ssl-certificate=/var/lib/arvados/self-signed.pem \
                  --ssl-certificate-key=/var/lib/arvados/self-signed.key
