# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

source 'https://rubygems.org'
gemspec
group :test, :performance do
  gem 'minitest', '>= 5.0.0'
  gem 'mocha', '>= 1.5.0', require: false
  gem 'rake'
end
