#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh

cd /usr/src/arvados/doc
run_bundler --without=development

cd /usr/src/arvados/sdk/R
R --quiet --vanilla --file=install_deps.R

if test "$1" = "--only-deps" ; then
    exit
fi

set -u

cat <<EOF >/var/lib/arvados/doc-nginx.conf
worker_processes auto;
pid /var/lib/arvados/doc-nginx.pid;

error_log stderr;
daemon off;

events {
	worker_connections 64;
}

http {
     access_log off;
     include /etc/nginx/mime.types;
     default_type application/octet-stream;
     server {
            listen ${services[doc]} default_server;
            listen [::]:${services[doc]} default_server;
            root /usr/src/arvados/doc/.site;
            index index.html;
            server_name _;
     }
}
EOF

cd /usr/src/arvados/doc
bundle exec rake generate baseurl=http://$localip:${services[doc]} arvados_api_host=$localip:${services[api]} arvados_workbench_host=http://$localip

exec nginx -c /var/lib/arvados/doc-nginx.conf
