#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh

if test "$1" != "--only-deps" ; then
  while [ ! -f $ARVADOS_CONTAINER_PATH/api.ready ]; do
    sleep 1
  done
fi

cd /usr/src/arvados/doc
run_bundler --without=development

# Generating the R docs is expensive, so for development if the file
# "no-sdk" exists then skip the R stuff.
if [[ ! -f /usr/src/arvados/doc/no-sdk ]] ; then
    cd /usr/src/arvados/sdk/R
    R --quiet --vanilla --file=install_deps.R
fi

if test "$1" = "--only-deps" ; then
    exit
fi

cd /usr/src/arvados/doc
flock $GEMLOCK bundle exec rake generate baseurl=http://$localip:${services[doc]} arvados_api_host=$localip:${services[controller-ssl]} arvados_workbench_host=http://$localip
