# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# These values are used to build Arvados dashboards.
arvados_grafana_tls_goodtime: "{{ 40 * 24 * 60 * 60 }}"
arvados_grafana_tls_warntime: "{{ 20 * 24 * 60 * 60 }}"
arvados_grafana_datasources:
  Loki:
    type: loki
    uid: ArvadosLokiDataSource
  Prometheus:
    type: prometheus
    uid: ArvadosPromDataSource
