#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

set -e

.  /usr/local/lib/arvbox/common.sh

/usr/local/lib/arvbox/runsu.sh $0-service $1

cd /usr/src/arvados/apps/workbench

rm -rf tmp
mkdir tmp
chown arvbox:arvbox tmp

if test -s /var/lib/arvados/workbench_rails_env ; then
  export RAILS_ENV=$(cat /var/lib/arvados/workbench_rails_env)
else
  export RAILS_ENV=development
fi

if test "$1" != "--only-deps" ; then
    exec bundle exec passenger start --port=${services[workbench]} \
         --user arvbox
fi
