#!/bin/sh
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

set -e

/usr/local/lib/arvbox/runsu.sh $0-service $1

cd /usr/src/arvados/apps/workbench

rm -rf tmp
mkdir tmp
chown arvbox:arvbox tmp

if test "$1" != "--only-deps" ; then
    exec bundle exec passenger start --port 80 \
         --user arvbox --runtime-dir=/var/lib/passenger
fi
