#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

.  /usr/local/lib/arvbox/common.sh

if test "$1" != "--only-deps" ; then
  while [ ! -f $ARVADOS_CONTAINER_PATH/api.ready ]; do
    sleep 1
  done
fi

cd /usr/src/arvados/apps/workbench

if test -s $ARVADOS_CONTAINER_PATH/workbench_rails_env ; then
  export RAILS_ENV=$(cat $ARVADOS_CONTAINER_PATH/workbench_rails_env)
else
  export RAILS_ENV=development
fi

run_bundler --without=development
flock $GEM_HOME/gems.lock bin/passenger-config build-native-support
flock $GEM_HOME/gems.lock bin/passenger-config install-standalone-runtime
mkdir -p /usr/src/arvados/apps/workbench/tmp

if test "$1" = "--only-deps" ; then
   # Workaround for validation that asserts there's a download URL
   # configured, which breaks rake if it is missing.
cat >config/application.yml <<EOF
$RAILS_ENV:
  keep_web_url: https://example.com/c=%{uuid_or_pdh}
EOF
   RAILS_GROUPS=assets flock $GEM_HOME/gems.lock bin/bundle exec rake npm:install
   rm config/application.yml
   exit
fi

set -u

secret_token=$(cat $ARVADOS_CONTAINER_PATH/workbench_secret_token)

RAILS_GROUPS=assets flock $GEM_HOME/gems.lock bin/bundle exec rake npm:install
flock $GEM_HOME/gems.lock bin/bundle exec rake assets:precompile
