#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

flock /var/lib/arvados/createusers.lock /usr/local/lib/arvbox/createusers.sh

make-ssl-cert generate-default-snakeoil --force-overwrite

. /usr/local/lib/arvbox/common.sh

chown -R $PGUSER:$PGGROUP /var/lib/postgresql
chown -R $PGUSER:$PGGROUP /var/run/postgresql
chown -R $PGUSER:$PGGROUP /etc/postgresql
chown -R $PGUSER:$PGGROUP /etc/ssl/private
chmod -R g-r /etc/ssl/private

exec chpst -u $PGUSER:$PGGROUP $0-service
