#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -eux -o pipefail

PGVERSION=$(psql --version | grep -E -o '[0-9]+' | head -n1)

if ! test -d /var/lib/postgresql/$PGVERSION/main ; then
    /usr/lib/postgresql/$PGVERSION/bin/initdb --locale=en_US.UTF-8 -D /var/lib/postgresql/$PGVERSION/main
fi
mkdir -p /var/run/postgresql/$PGVERSION-main.pg_stat_tmp

rm -f /var/lib/postgresql/$PGVERSION/main/postmaster.pid

exec /usr/lib/postgresql/$PGVERSION/bin/postgres -D /var/lib/postgresql/$PGVERSION/main -c config_file=/etc/postgresql/$PGVERSION/main/postgresql.conf
