{
 "title": "Arvados cluster overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Earliest SSL certificate expiration",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "min(probe_ssl_earliest_cert_expiry)-time()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepstore bandwidth [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(arvados_keepstore_volume_io_bytes{}[1m])) without (operation,device_id)",
     "legendFormat": "{{ instance }} {{ direction }}"
    }
   ]
  },
  {
   "title": "Containers running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arvados_dispatchcloud_containers_running{}",
     "legendFormat": "# containers"
    }
   ]
  },
  {
   "title": "Keepstore volume operations rate/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(arvados_keepstore_volume_operations{}[1m])) without (operation,device_id)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queue: # containers per {state, instance type}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arvados_dispatchcloud_queue_entries{}",
     "legendFormat": "{{instance_type}} {{state}}"
    },
    {
     "expr": "arvados_dispatchcloud_containers_allocated_not_started{}",
     "legendFormat": "allocated, not started"
    },
    {
     "expr": "arvados_dispatchcloud_containers_not_allocated_over_quota{}",
     "legendFormat": "not allocated, over quota"
    }
   ]
  },
  {
   "title": "Keepstore buffers in use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arvados_keepstore_bufferpool_inuse_buffers{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container wait times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "arvados_dispatchcloud_containers_longest_wait_time_seconds{}",
     "legendFormat": "Longest wait time"
    },
    {
     "expr": "rate(arvados_dispatchcloud_containers_time_from_queue_to_crunch_run_seconds_sum{}[10m]) / rate(arvados_dispatchcloud_containers_time_from_queue_to_crunch_run_seconds_count{}[10m])",
     "legendFormat": "avg wait time [10m]"
    }
   ]
  },
  {
   "title": "Total bytes by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "arvados_keep_total_bytes{}", "legendFormat": "Total stored" },
    {
     "expr": "arvados_keep_overreplicated_bytes{}",
     "legendFormat": "Overreplicated"
    },
    {
     "expr": "arvados_keep_underreplicated_bytes{}",
     "legendFormat": "Underreplicated"
    },
    { "expr": "arvados_keep_lost_bytes{}", "legendFormat": "Lost" }
   ]
  },
  {
   "title": "Instance time to ... avg [10m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(arvados_dispatchcloud_instances_time_to_ssh_seconds_sum{}[10m]) / rate(arvados_dispatchcloud_instances_time_to_ssh_seconds_count{}[10m])",
     "legendFormat": "ssh"
    },
    {
     "expr": "rate(arvados_dispatchcloud_instances_time_to_ready_for_container_seconds_sum{}[10m]) / rate(arvados_dispatchcloud_instances_time_to_ready_for_container_seconds_count{}[10m])",
     "legendFormat": "ready"
    }
   ]
  },
  {
   "title": "Concurrent requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "arvados_concurrent_requests{}", "legendFormat": "{{instance}}_{{queue}}" }
   ]
  },
  {
   "title": "Boot outcomes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arvados_dispatchcloud_boot_outcomes{}",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "$ / hour" }
   ],
   "targets": [
    {
     "expr": "sum(arvados_dispatchcloud_instances_price{})",
     "legendFormat": "cost ($)"
    }
   ]
  },
  {
   "title": "instance state before disappearance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arvados_dispatchcloud_instances_disappeared{}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cost by node state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "$ / hour" }
   ],
   "targets": [
    {
     "expr": "arvados_dispatchcloud_instances_price{}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Instances time from shutdown to disappearance avg[10m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(arvados_dispatchcloud_instances_time_from_shutdown_request_to_disappearance_seconds_sum{}[10m]) / rate(arvados_dispatchcloud_instances_time_from_shutdown_request_to_disappearance_seconds_count{}[10m])",
     "legendFormat": "shutdown to disappearance"
    }
   ]
  },
  {
   "title": "Nodes by state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arvados_dispatchcloud_instances_total{}",
     "legendFormat": "{{instance_type}} : {{category}}"
    }
   ]
  },
  {
   "title": "run probe duration avg[10m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(arvados_dispatchcloud_instances_run_probe_duration_seconds_sum{}[10m]) / rate(arvados_dispatchcloud_instances_run_probe_duration_seconds_count{}[10m])",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "run probe count by outcome -- delta[1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(arvados_dispatchcloud_instances_run_probe_duration_seconds_count{}[1m])",
     "legendFormat": "{{outcome}}"
    }
   ]
  }
 ]
}