#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh

if test -s /var/lib/arvados/api_rails_env ; then
  RAILS_ENV=$(cat /var/lib/arvados/api_rails_env)
else
  RAILS_ENV=development
fi

. /usr/local/lib/arvbox/go-setup.sh

flock /var/lib/gopath/gopath.lock go get -t "git.curoverse.com/arvados.git/services/ws"
install $GOPATH/bin/ws /usr/local/bin/arvados-ws

if test "$1" = "--only-deps" ; then
    exit
fi

database_pw=$(cat /var/lib/arvados/api_database_pw)

cat >/var/lib/arvados/arvados-ws.yml <<EOF
Client:
  APIHost: $localip:${services[api]}
  Insecure: true
Postgres:
  dbname: arvados_$RAILS_ENV
  user: arvados
  password: $database_pw
  host: localhost
Listen: :8002
EOF

exec /usr/local/bin/arvados-ws -config /var/lib/arvados/arvados-ws.yml
