#!/bin/bash
# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

exec 2>&1
set -ex -o pipefail

. /usr/local/lib/arvbox/common.sh

mkdir -p /var/lib/gopath
cd /var/lib/gopath

export GOPATH=$PWD
mkdir -p "$GOPATH/src/git.curoverse.com"
ln -sfn "/usr/src/arvados" "$GOPATH/src/git.curoverse.com/arvados.git"
flock /var/lib/gopath/gopath.lock go get -t "git.curoverse.com/arvados.git/services/ws"
install bin/ws /usr/local/bin/arvados-ws

if test "$1" = "--only-deps" ; then
    exit
fi

database_pw=$(cat /var/lib/arvados/api_database_pw)

cat >/var/lib/arvados/arvados-ws.yml <<EOF
Client:
  APIHost: $localip:${services[api]}
  Insecure: true
Postgres:
  dbname: arvados_development
  user: arvados
  password: $database_pw
  host: localhost
Listen: :8002
EOF

exec /usr/local/bin/arvados-ws -config /var/lib/arvados/arvados-ws.yml
